#Server Setting
server:
  port: 80
  servlet:
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    threads:
      min-spare: 30

#Setting For Spring
spring:
  #Spring to DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/administration?serverTimezone=UTC&characterEncoding=UTF-8
    username: administration
    password: fldh6323
  #Spring Data JPA Setting
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true